### ISSUE TITLE
Number reported in "Tegenpartij bij ongelukken" differs in tooltip and matrix

### ISSUE THREAD

**Issue by b-a0** [digitaldutch/roaddanger.org#10]
Steps to reproduce:

1. Visit https://nl.roaddanger.org/
2. Via the hamburger menu go to "Tegenpartij bij ongelukken"
3. Ensure the filters are in effect as shown in the screenshot.
4. Hover over the bicycle number (210 at time of writing):
![image](https://github.com/digitaldutch/roaddanger.org/assets/25707742/cb750ca1-84a4-449a-b2a1-54b776bc1f41)

The hover shows 213 deaths, while the matrix shows 210.
Similarly this happens with the eenzijdig x autododen:

![image](https://github.com/digitaldutch/roaddanger.org/assets/25707742/d6fc15a5-4ac6-45f0-bf2b-2599549ba189)

**Comment by digitaldutch** [comment]
You got a sharp eye. It is fixed in the latest version.

The reason for the difference is that the number in the circle was rounded, while the tooltip shows the exact number. The reason for this is that long numbers don't fit in the circle. The goal is to make larger number like 12345 show up as 12.3K.

The tooltip now shows the same rounded number.
